(require 'latex)
(load "auctex.el" nil t t)
(set 'TeX-auto-save t)
(set 'TeX-parse-self t)
(setq-default TeX-master nil)
(latex-preview-pane-enable)
(set 'doc-view-continuous t)
(require 'company-auctex)
(company-auctex-init)
(provide 'setup-latex)
